const studentMock = [
  {
    id: 1,
    name: "Ricky Martin",
    studentId: 20,
    email: "ricky@abc.com",
    phone: 9988998899,
    location: "India",
    gender: "Male",
  },
  {
    id: 2,
    name: "Harvery Spector",
    studentId: 24,
    email: "harvery@aaa.com",
    phone: 8877667788,
    location: "USA",
    gender: "Male",
  },
  {
    id: 3,
    name: "Mike Ross",
    studentId: 19,
    email: "mike@nnn.com",
    phone: 7878675645,
    location: "UK",
    gender: "Male",
  },
  {
    id: 4,
    name: "Rachel Hassan",
    studentId: 2888,
    email: "rachel@kkk.com",
    phone: 6878787878,
    location: "Swiss",
    gender: "Female",
  },
  {
    id: 5,
    name: "Jeni Hale",
    studentId: 822,
    email: "jeni@olo.com",
    phone: 9192939495,
    location: "China",
    gender: "Female",
  },
  {
    id: 6,
    name: "Louis Tyson",
    studentId: 73,
    email: "louis@test.com",
    phone: 6878551234,
    location: "Netherlands",
    gender: "Male",
  },
  {
    id: 7,
    name: "Tori Vega",
    studentId: 112,
    email: "tori@dd.com",
    phone: 7674325431,
    location: "Afghanistan",
    gender: "Female",
  },
  {
    id: 8,
    name: "Jade West",
    studentId: 343,
    email: "Jade@gaa.com",
    phone: 7699880906,
    location: "Belgium",
    gender: "Female",
  },
];

const headCells = [
  {
    id: "name",
    numeric: false,
    disablePadding: true,
    label: "Name",
  },
  {
    id: "studentId",
    numeric: false,
    disablePadding: true,
    label: "Student Id",
  },
  {
    id: "email",
    numeric: false,
    disablePadding: false,
    label: "Email",
  },
  {
    id: "phone",
    numeric: false,
    disablePadding: false,
    label: "Phone",
  },
  {
    id: "location",
    numeric: false,
    disablePadding: false,
    label: "Location",
  },
  {
    id: "gender",
    numeric: false,
    disablePadding: false,
    label: "Gender",
  },
];
export { studentMock, headCells };
